const exerciseList = [
    { name: "burpees", difficulty: "hard", bodyPart: ["full body"], dynamic: true },
    { name: "push up", difficulty: "medium", bodyPart: ["upper body", "arms"], dynamic: true },
    { name: "squat", difficulty: "easy", bodyPart: ["legs"], dynamic: true },
    { name: "crunch", difficulty: "easy", bodyPart: ["abs"], dynamic: false },
    { name: "jumping jack", difficulty: "easy", bodyPart: ["full body"], dynamic: true },
    { name: "russian twist", difficulty: "medium", bodyPart: ["abs"], dynamic: false },
    { name: "mountain climber", difficulty: "easy", bodyPart: ["full body"], dynamic: true },
    { name: "plank", difficulty: "easy", bodyPart: ["abs"], dynamic: false },
    { name: "lunges", difficulty: "easy", bodyPart: ["legs"], dynamic: true },
    { name: "high knees", difficulty: "medium", bodyPart: ["legs"], dynamic: true },
    { name: "jump rope", difficulty: "easy", bodyPart: ["full body"], dynamic: true },
    { name: "diamond push ups", difficulty: "hard", bodyPart: ["upper body", "arms"], dynamic: true },
    { name: "sit ups", difficulty: "medium", bodyPart: ["abs"], dynamic: false },
    { name: "pull ups", difficulty: "hard", bodyPart: ["upper body", "arms"], dynamic: true },
    { name: "L-sit", difficulty: "hard", bodyPart: ["abs"], dynamic: false },
    { name: "wall sit", difficulty: "medium", bodyPart: ["legs"], dynamic: false },
    { name: "calf raises", difficulty: "easy", bodyPart: ["legs"], dynamic: true },
    { name: "side plank", difficulty: "medium", bodyPart: ["abs", "side"], dynamic: false },
    { name: "superman", difficulty: "medium", bodyPart: ["back", "upper body"], dynamic: false },
    { name: "hamstring curl", difficulty: "medium", bodyPart: ["legs"], dynamic: false },
    { name: "wide push ups", difficulty: "medium", bodyPart: ["upper body", "arms"], dynamic: true },
    { name: "flutterkicks", difficulty: "medium", bodyPart: ["abs"], dynamic: false },
    { name: "pistol squats", difficulty: "hard", bodyPart: ["legs"], dynamic: true },
    { name: "hip thrust", difficulty: "medium", bodyPart: ["legs"], dynamic: true },
    { name: "one leg lunge", difficulty: "hard", bodyPart: ["legs"], dynamic: true },
    { name: "bulgarian squat", difficulty: "hard", bodyPart: ["legs"], dynamic: true },
    { name: "jump lunges", difficulty: "hard", bodyPart: ["legs"], dynamic: true },
    { name: "bear walk", difficulty: "medium", bodyPart: ["full body"], dynamic: true },
    { name: "step up", difficulty: "medium", bodyPart: ["legs"], dynamic: true },
    { name: "crab walk", difficulty: "medium", bodyPart: ["full body"], dynamic: true },
    { name: "archer push ups", difficulty: "hard", bodyPart: ["upper body", "arms"], dynamic: true },
    { name: "knee push ups", difficulty: "easy", bodyPart: ["upper body", "arms"], dynamic: true },
    { name: "jumping squat", difficulty: "medium", bodyPart: ["legs"], dynamic: true },
    { name: "toe touches", difficulty: "easy", bodyPart: ["abs"], dynamic: false },
    { name: "high plank", difficulty: "medium", bodyPart: ["abs"], dynamic: false },
    { name: "wall assisted handstand hold", difficulty: "hard", bodyPart: ["upper body", "arms"], dynamic: false },
    { name: "wall assisted handstand push up", difficulty: "extreme", bodyPart: ["upper body", "arms"], dynamic: true },
    { name: "L-sit", difficulty: "hard", bodyPart: ["abs"], dynamic: false },
    { name: "pike push up", difficulty: "hard", bodyPart: ["upper body", "arms"], dynamic: true },
    { name: "skater jump", difficulty: "medium", bodyPart: ["legs"], dynamic: true },
    { name: "courtesy lunge", difficulty: "medium", bodyPart: ["legs"], dynamic: true },
    { name: "jump lunges", difficulty: "hard", bodyPart: ["legs"], dynamic: true },
    { name: "duck walk", difficulty: "medium", bodyPart: ["legs"], dynamic: true },
    { name: "side squat", difficulty: "medium", bodyPart: ["legs"], dynamic: true },
    { name: "fast foot shuffle", difficulty: "medium", bodyPart: ["legs"], dynamic: true },
    { name: "dead bug", difficulty: "medium", bodyPart: ["abs"], dynamic: false },
    { name: "half burpees", difficulty: "medium", bodyPart: ["full body"], dynamic: true },
    { name: "one arm push up", difficulty: "extreme", bodyPart: ["upper body", "arms"], dynamic: true },
    { name: "double tap twist crunch", difficulty: "medium", bodyPart: ["abs"], dynamic: false },
    { name: "side plank crunch", difficulty: "medium", bodyPart: ["abs", "side"], dynamic: false },
    { name: "leg raises", difficulty: "medium", bodyPart: ["abs"], dynamic: false },
    { name: "run in place", difficulty: "easy", bodyPart: ["legs"], dynamic: true },
    { name: "in & out", difficulty: "medium", bodyPart: ["abs"], dynamic: false },
    { name: "wide push ups", difficulty: "medium", bodyPart: ["upper body", "arms"], dynamic: true },
    { name: "high side plank raise", difficulty: "medium", bodyPart: ["abs", "side"], dynamic: false },
    { name: "push up side to side", difficulty: "medium", bodyPart: ["upper body", "arms"], dynamic: true },
    { name: "side to side jump squat", difficulty: "easy", bodyPart: ["legs"], dynamic: true },
    { name: "plank up & down", difficulty: "easy", bodyPart: ["abs"], dynamic: false },
    { name: "seated in & out", difficulty: "medium", bodyPart: ["abs"], dynamic: false },
    { name: "butt kicks", difficulty: "easy", bodyPart: ["legs"], dynamic: true },
    { name: "plank side to side", difficulty: "medium", bodyPart: ["abs"], dynamic: false },
    { name: "squat taps", difficulty: "medium", bodyPart: ["legs"], dynamic: true },
    { name: "crunch reach through", difficulty: "medium", bodyPart: ["abs"], dynamic: false },
    { name: "plank alternating leg raise", difficulty: "easy", bodyPart: ["abs"], dynamic: false },
    { name: "boat hold", difficulty: "medium", bodyPart: ["abs"], dynamic: false },
    { name: "side boat hold", difficulty: "medium", bodyPart: ["abs", "side"], dynamic: false },
  ];
  
export default exerciseList;
