const exerciseList = [
    { name: "burpees", difficulty: "hard", bodyPart: ["full body"], dynamic: true },
    { name: "push up", difficulty: "medium", bodyPart: ["upper body", "arms"], dynamic: true },
    { name: "squat", difficulty: "medium", bodyPart: ["legs"], dynamic: true },
    { name: "crunch", difficulty: "easy", bodyPart: ["abs"], dynamic: false },
    { name: "jumping jack", difficulty: "medium", bodyPart: ["full body"], dynamic: true },
    { name: "russian twist", difficulty: "medium", bodyPart: ["abs"], dynamic: false },
    { name: "mountain climber", difficulty: "hard", bodyPart: ["full body"], dynamic: true },
    { name: "plank", difficulty: "medium", bodyPart: ["abs"], dynamic: false },
    { name: "lunges", difficulty: "medium", bodyPart: ["legs"], dynamic: true },
    { name: "high knees", difficulty: "medium", bodyPart: ["legs"], dynamic: true },
    { name: "jump rope", difficulty: "medium", bodyPart: ["full body"], dynamic: true },
    { name: "diamond push ups", difficulty: "hard", bodyPart: ["upper body", "arms"], dynamic: true },
    { name: "sit ups", difficulty: "medium", bodyPart: ["abs"], dynamic: false },
    { name: "pull ups", difficulty: "hard", bodyPart: ["upper body", "arms"], dynamic: true },
    { name: "L-sit", difficulty: "hard", bodyPart: ["abs"], dynamic: false },
    { name: "wall sit", difficulty: "medium", bodyPart: ["legs"], dynamic: false },
    { name: "calf raises", difficulty: "easy", bodyPart: ["legs"], dynamic: true },
    { name: "side plank", difficulty: "medium", bodyPart: ["abs", "side"], dynamic: false },
    { name: "superman", difficulty: "medium", bodyPart: ["back"], dynamic: false },
    { name: "hamstring curl", difficulty: "medium", bodyPart: ["legs"], dynamic: false },
    { name: "wide push ups", difficulty: "medium", bodyPart: ["upper body", "arms"], dynamic: true },
    { name: "flutterkicks", difficulty: "medium", bodyPart: ["abs"], dynamic: false },
    { name: "pistol squats", difficulty: "hard", bodyPart: ["legs"], dynamic: true },
    { name: "hip thrust", difficulty: "medium", bodyPart: ["legs"], dynamic: true },
    { name: "one leg lunge", difficulty: "hard", bodyPart: ["legs"], dynamic: true },
    { name: "bulagarian squat", difficulty: "hard", bodyPart: ["legs"], dynamic: true },
    { name: "jump lunges", difficulty: "hard", bodyPart: ["legs"], dynamic: true },
    { name: "bear walk", difficulty: "medium", bodyPart: ["full body"], dynamic: true },
    { name: "step up", difficulty: "medium", bodyPart: ["legs"], dynamic: true },
    { name: "crab walk", difficulty: "medium", bodyPart: ["full body"], dynamic: true },
    { name: "archer push ups", difficulty: "hard", bodyPart: ["upper body", "arms"], dynamic: true }
  ];
  
export default exerciseList;
